# TCL File Generated by Component Editor 18.1
# Thu Apr 23 00:16:44 CDT 2020
# DO NOT MODIFY


# 
# Avalon "Avalon" v1.0
#  2020.04.23.00:16:44
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Avalon
# 
set_module_property DESCRIPTION ""
set_module_property NAME Avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Avalon
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL new_component
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_interface.sv SYSTEM_VERILOG PATH modules/avalon_interface.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_interface.sv SYSTEM_VERILOG PATH modules/avalon_interface.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point CLK
# 
add_interface CLK clock end
set_interface_property CLK clockRate 50000000
set_interface_property CLK ENABLED true
set_interface_property CLK EXPORT_OF ""
set_interface_property CLK PORT_NAME_MAP ""
set_interface_property CLK CMSIS_SVD_VARIABLES ""
set_interface_property CLK SVD_ADDRESS_GROUP ""

add_interface_port CLK CLK clk Input 1


# 
# connection point RESET
# 
add_interface RESET reset end
set_interface_property RESET associatedClock CLK
set_interface_property RESET synchronousEdges DEASSERT
set_interface_property RESET ENABLED true
set_interface_property RESET EXPORT_OF ""
set_interface_property RESET PORT_NAME_MAP ""
set_interface_property RESET CMSIS_SVD_VARIABLES ""
set_interface_property RESET SVD_ADDRESS_GROUP ""

add_interface_port RESET RESET reset Input 1


# 
# connection point AVALON_SLAVE
# 
add_interface AVALON_SLAVE avalon end
set_interface_property AVALON_SLAVE addressUnits WORDS
set_interface_property AVALON_SLAVE associatedClock CLK
set_interface_property AVALON_SLAVE associatedReset RESET
set_interface_property AVALON_SLAVE bitsPerSymbol 8
set_interface_property AVALON_SLAVE burstOnBurstBoundariesOnly false
set_interface_property AVALON_SLAVE burstcountUnits WORDS
set_interface_property AVALON_SLAVE explicitAddressSpan 0
set_interface_property AVALON_SLAVE holdTime 0
set_interface_property AVALON_SLAVE linewrapBursts false
set_interface_property AVALON_SLAVE maximumPendingReadTransactions 0
set_interface_property AVALON_SLAVE maximumPendingWriteTransactions 0
set_interface_property AVALON_SLAVE readLatency 0
set_interface_property AVALON_SLAVE readWaitStates 0
set_interface_property AVALON_SLAVE readWaitTime 0
set_interface_property AVALON_SLAVE setupTime 0
set_interface_property AVALON_SLAVE timingUnits Cycles
set_interface_property AVALON_SLAVE writeWaitTime 0
set_interface_property AVALON_SLAVE ENABLED true
set_interface_property AVALON_SLAVE EXPORT_OF ""
set_interface_property AVALON_SLAVE PORT_NAME_MAP ""
set_interface_property AVALON_SLAVE CMSIS_SVD_VARIABLES ""
set_interface_property AVALON_SLAVE SVD_ADDRESS_GROUP ""

add_interface_port AVALON_SLAVE AVL_ADDR address Input 4
add_interface_port AVALON_SLAVE AVL_BYTE_EN byteenable Input 4
add_interface_port AVALON_SLAVE AVL_READ read Input 1
add_interface_port AVALON_SLAVE AVL_WRITE write Input 1
add_interface_port AVALON_SLAVE AVL_READDATA readdata Output 32
add_interface_port AVALON_SLAVE AVL_WRITEDATA writedata Input 32
add_interface_port AVALON_SLAVE AVL_CS chipselect Input 1
set_interface_assignment AVALON_SLAVE embeddedsw.configuration.isFlash 0
set_interface_assignment AVALON_SLAVE embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment AVALON_SLAVE embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment AVALON_SLAVE embeddedsw.configuration.isPrintableDevice 0

